import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Header from "../component/Header";
import HeroContainer from "../component/HeroContainer";
import BlogSection from "../component/BlogSection";
import Footer from "../component/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dev Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroContainer />
      <BlogSection />
    </div>
  );
}
